language: node_js
repo_token: $repo_token


node_js:
    - "10"

cache:
  directories:
    - "node_modules"

install:
  - npm install

before_script:
  - npm run test:travis-cov

script:
  - npm run build
